---
format:
  typstdoc-typst:
    title: "Typst Document Title"
    footer: "Running Footer"
    papersize: "us-letter"
    columns: 2
    margin:
      x: 1in
      top: 1in
      bottom: 1.25in
    authors: "Author Name"
    mainfont: "Roboto"
    monofont: "Roboto Mono"
    fontsize: 1em
    fontfill: blue
    title-align: left
    title-size: 2.5em
    title-inset: 0.25em
    page-numbering: "1/1"
    page-number-align: right + bottom
    list-indent: 1em
---

# Heading 1

## Heading 2

This template shows the use of the `fontfill`, `page-numbering`, `flipped`, and `page-number-align` parameters.

## More Information

You can learn more about creating custom Typst templates here: 

<https://quarto.org/docs/prerelease/1.4/typst.html#custom-formats>

:::{.callout-note collapse=false appearance='default' icon=true}
## Optional caption (note)
- Hide callout body with 'collapse=true'
- Remove 'collapse' to prevent expandability
- Set appearance to 'default', 'simple' or 'minimal'
- Remove icon with 'icon=false'
:::

### Heading 3

Etiam ullamcorper neque sed sapien viverra consequat vel sit amet ipsum. Vivamus faucibus vestibulum lacus, in sollicitudin ipsum ullamcorper ac. Proin et rutrum nibh. Donec id justo in elit sollicitudin fermentum et at sem.

1. Etiam sed nibh at elit euismod suscipit.
2. Nulla quis leo ullamcorper, mollis mauris vel, tristique sapien.
3. Nulla facilisi.

#### Heading 4

Aenean pretium dui libero, vitae consectetur quam rhoncus ut. Nullam turpis eros, lobortis id mi eget, euismod aliquet ligula. Integer non diam vitae ipsum faucibus cursus. Donec nisl quam, faucibus a sapien sed, tincidunt condimentum eros. Etiam porta, ligula quis dignissim gravida, ante dolor maximus tortor, at aliquet nibh risus vitae nunc.

Curabitur ut tempor libero, at luctus libero. Duis nec arcu non arcu vulputate fermentum in nec augue. In leo tortor, aliquet eget massa nec, aliquam tempor diam.

- Duis tincidunt viverra tortor, sit amet dictum ante iaculis in. Aliquam ut neque vitae eros aliquam luctus. Proin leo nisl, interdum eget ipsum eu, lacinia vestibulum ligula.
- Phasellus ac orci vel ex hendrerit pulvinar. Fusce tincidunt non augue sit amet pulvinar. Sed fringilla nisi mi, at lacinia eros tristique eget.

Duis molestie eleifend velit vitae gravida. Aenean eget finibus lectus. Praesent gravida dolor eu justo rhoncus, nec ultrices urna convallis. Fusce id varius ipsum, sit amet tempus ante. Morbi sit amet lobortis ex, id efficitur ex.

>Praesent vestibulum libero quis lacus mollis finibus. Aenean sed tortor ut urna faucibus sodales.

Donec facilisis rutrum commodo. Vivamus mattis volutpat erat, ac vestibulum magna consectetur et. Quisque scelerisque metus in tellus efficitur, ac efficitur dui volutpat. Nam ut dui consequat velit pulvinar blandit venenatis sed elit. Ut consequat tincidunt lorem ut fringilla. Sed luctus, diam vel convallis gravida, enim turpis condimentum est, quis porta turpis libero ac ipsum.

Suspendisse magna magna, viverra luctus lectus eget, ultricies lobortis lacus. Integer elementum odio vel dignissim commodo. Ut ut dignissim eros. Nam ut arcu eleifend, hendrerit nisi eu, dictum nisi. Suspendisse id tellus consectetur, malesuada tortor in, faucibus arcu. Sed sagittis ligula vitae ex posuere vulputate. Fusce sit amet sagittis nulla. Phasellus convallis eros mauris, eu commodo magna pretium eu. Sed at leo condimentum, suscipit sapien sit amet, semper erat.

::: {.block fill="luma(230)" inset="1.5em" radius="0.5em"}

This is a block with gray background and slightly rounded corners.

:::

Sed finibus rhoncus elit, eu dictum augue suscipit et. Nulla eu erat vitae est egestas euismod. Aliquam erat volutpat. Nulla mattis id nisl eu euismod. Morbi sed rutrum ipsum. Pellentesque facilisis gravida felis, ac feugiat lectus commodo sit amet. Sed diam nisl, tempus eu risus ac, hendrerit tempor justo. Nullam mollis ligula ac vestibulum aliquet.